name: update-feeds
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r backend/requirements.txt
      - run: python backend/feeder.py
      - run: |
          git config user.email "rss-bot@users.noreply.github.com"
          git config user.name  "rss-bot"
          git add backend/content.db
          git commit -m "auto: refresh feeds $(date -u)" || true
          git push 